### ISSUE TITLE
Headers dont't seem to be associated with header variable

### ISSUE THREAD

**Issue by vandelin586** [umn-microsoft-automation/UMN-SplunkRA#13]
Headers dont't seem to be associated with header variable

Assigning $headers=splunk-connect is null but it is needed for Get-SplunkSearchJobsResults

**Comment by kylecweeks** [comment]
Hi,

The cmdlet is connect-splunk vs the example you provided of splunk-connect

## Authenticate and get token
$cred = Get-Credential
$server = 'splunk.yourdomain.net'
$header = Connect-Splunk -splunkCreds $cred  -server $server

Please be aware that the default port for Splunk is important as well. 8089 is default, and can also be specified in the header request if you do not use standard ports.

**Comment by vandelin586** [comment]
I did not even notice my mistake. Thank you this is resolved
