### ISSUE TITLE
%sid%/results?count=0 , 

### ISSUE THREAD

**Issue by vandelin586** [umn-microsoft-automation/UMN-SplunkRA#14]
Using curl and i query my saved report, if i add /results?count=0 on the end of my sid it returns all data in the report. If you dont set this it only returns about 1000

By using get-splunksearchjobsresults is there a way i can get the whole report?
It seems to just grab 100 , im expecting about 40K

Any ideas how i can get more than 100 lines?
``
, if a place /results?count=0 at the end of my sid
 it throws this error

 `:`Invoke-WebRequest : 
  
    Invalid count.
  
At C:\Program Files\WindowsPowerShell\Modules\UMN-SplunkRA-master\UMN-SplunkRA.psm1:155 char:23
+ ... se{$data = (Invoke-WebRequest -Uri $uri -Headers $header -UseBasicPar ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ConvertFrom-Csv : Cannot validate argument on parameter 'InputObject'. The argument is null. Provide a valid value for the argument, and then try running the command again.
At C:\Program Files\WindowsPowerShell\Modules\UMN-SplunkRA-master\UMN-SplunkRA.psm1:156 char:53
+         if ($outPutmode -eq 'csv'){ return ($data | ConvertFrom-Csv)}
+                                                     ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Csv], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.ConvertFromCsvCommand``

**Comment by travis-sobeck** [comment]
I can take a look.

**Comment by travis-sobeck** [comment]
This should be a pretty straight forward adjustment to the module.

**Comment by travis-sobeck** [comment]
@vandelin586 go ahead and pull the latest version 1.0.8, I've added a param for resultSize.  you can set it to 0 to get all results.
