### ISSUE TITLE
Using Get-SplunkSearchJobsResults cuts off last two columns which is the time and date

### ISSUE THREAD

**Issue by vandelin586** [umn-microsoft-automation/UMN-SplunkRA#16]
When using get-splunksearchjobsresults the last two fields from my report are either missing or perhaps truncated. my saved report has four fields when i request my saved report through the module I only get two

**Comment by travis-sobeck** [comment]
Do you get all four when you use curl?

**Comment by travis-sobeck** [comment]
Also, have you tried piping it through format-list
Get-SplunkSearchJobsResults -server $server -header $header -sid $sid -resultSize 1 | Format-List

**Comment by vandelin586** [comment]
i did get all my data with curl, except my org does not want to install a higher version of curl that supports - -insecure or -k. The app im hitting does not have a valid cert and is not trusted.

I was trying other commands besides your module and curl and the report came out the same way, 2 missing columns. I was using powershell but anywayI can try format list tomorrow

**Comment by vandelin586** [comment]
Resolved! Thanks
